name: Terraform Multi-Env Multi-Region Pipeline

on:
  push:
    branches:
      - main

jobs:

  #  DEV (parallel across regions)
  deploy-dev:
    name: Deploy Dev
    strategy:
      matrix:
        region: [ap-south-1, us-west-1]

    uses: ./.github/workflows/terraform-reusable-pipeline.yml
    with:
      environment: dev
      aws_region: ${{ matrix.region }}

  #  QA (wait for ALL dev jobs)
  deploy-qa:
    name: Deploy QA
    needs: deploy-dev
    strategy:
      matrix:
        region: [us-east-1, ap-southeast-1]

    uses: ./.github/workflows/terraform-reusable-pipeline.yml
    with:
      environment: qa
      aws_region: ${{ matrix.region }}
