name: Terraform Multi-Env Multi-Region Pipeline

#on:
 # push:
  #  branches:
   #   - main

jobs:

  #  DEV (parallel across regions)
  deploy-dev:
    name: Deploy Dev
    strategy:
      matrix:
        region: [ap-south-1, us-west-1]

    uses: ./.github/workflows/terraform-reusable-pipeline.yml
    with:
      environment: dev
      aws_region: ${{ matrix.region }}
    secrets: inherit
