name: Reusable Terraform CI/CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:

  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ inputs.aws_region }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_BACKEND_REGION: ap-south-1
      TF_VAR_aws_region: ${{ inputs.AWS_REGION }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_project: myapp
      TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ inputs.environment }}/${{ env.AWS_REGION }}/terraform.tfstate" \
            -backend-config="region=${{ env.TF_BACKEND_REGION }}"

      - name: Select/Create Workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || \
          terraform workspace new ${{ inputs.environment }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -var-file="${{ inputs.environment }}.tfvars" \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -out=tfplan-${{ env.AWS_REGION }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ inputs.environment }}-${{ env.AWS_REGION }}
          path: tfplan-${{ env.AWS_REGION }}


  terraform-cd:
    name: Terraform CD
    runs-on: ubuntu-latest
    needs: terraform-ci

    environment: ${{ inputs.environment }}

    env:
      AWS_REGION: ${{ inputs.aws_region }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_BACKEND_REGION: ap-south-1
      TF_VAR_aws_region: ${{ inputs.AWS_REGION }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_project: myapp
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ inputs.environment }}/${{ env.AWS_REGION }}/terraform.tfstate" \
            -backend-config="region=${{ env.TF_BACKEND_REGION }}"

      - name: Select/Create Workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || \
          terraform workspace new ${{ inputs.environment }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ inputs.environment }}-${{ env.AWS_REGION }}
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan-${{ env.AWS_REGION }}

      - name: Wait for stabilization
        run: sleep 300   # 5 mins

      - name: Extract Terraform Outputs
        run: terraform output -json > outputs.json

      - name: Upload Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfoutput-${{ inputs.environment }}-${{ env.AWS_REGION }}
          path: outputs.json
